function data = importfile(workbookFile, sheetName, range)
%IMPORTFILE Import data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads all numeric data from the first worksheet
%   in the Microsoft Excel spreadsheet file named FILE and returns the
%   numeric data.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE(FILE,SHEET,RANGE) reads from the specified worksheet
%   and from the specified RANGE. Specify RANGE using the syntax
%   'C1:C2',where C1 and C2 are opposing corners of the region.%
% Example:
%   Mappe2 = importfile('Mappe2.xlsx','Tabelle1','A1:K30');
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2018/12/14 23:49:27

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If no range is specified, read all data
if nargin <= 2 || isempty(range)
    range = '';
end

%% Import the data
data = xlsread(workbookFile, sheetName, range);

